import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'data/models/task_model.dart';
import 'data/models/habit_model.dart';
import 'data/models/memory_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Hive local storage ────────────────────────────────────────────────────
  await Hive.initFlutter();

  // Register type adapters (generated by build_runner)
  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(TaskModelAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(HabitModelAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(MemoryEntryAdapter());
  if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(ChatMessageAdapter());

  // ── System UI ─────────────────────────────────────────────────────────────
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:                   Colors.transparent,
    statusBarIconBrightness:          Brightness.light,
    statusBarBrightness:              Brightness.dark,
    systemNavigationBarColor:         Colors.transparent,
    systemNavigationBarContrastEnforced: false,
  ));

  runApp(
    const ProviderScope(
      child: AiLifeOsApp(),
    ),
  );
}

class AiLifeOsApp extends ConsumerWidget {
  const AiLifeOsApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      title: 'AI Life OS',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      routerConfig: AppRouter.router,
      builder: (context, child) {
        return AnnotatedRegion<SystemUiOverlayStyle>(
          value: const SystemUiOverlayStyle(
            statusBarColor:           Colors.transparent,
            statusBarIconBrightness:  Brightness.light,
            statusBarBrightness:      Brightness.dark,
            systemNavigationBarColor: Colors.transparent,
          ),
          child: child!,
        );
      },
    );
  }
}
